lib/lita/services/lunch_assigner.rb, lib/lita/services/spreadsheet_writer.rb, spec/lita/services/spreadsheet_writer_spec.rb
Considera:
> Se guarda ahora periodicamente la gente que almorzó en un spreadsheet guardado en google drive, con el formato dia | nombre | id
de la pull request #14 Historial de Almorzadores para separar fix y feat.
Además, se cambiaron los test para no probarlos directamente en el google drive.
feat(persist_winners) code by: [Tewi](https://github.com/Tewi)
=> Write winners to spreadsheet

lib/lita/services/weighted_picker.rb
- Sacar `positive?` (es de la versión 2.3)
=> fix(weighted.picker): Remove positive? due to ruby version

lib/lita/handlers/api/api_controller.rb, lib/lita/handlers/api/karma.rb, lib/lita/handlers/lunch_reminder.rb, lib/lita/services/karmanager.rb, spec/lita/handlers/api/karma_spec.rb, spec/lita/handlers/api/lunch_spec.rb, spec/lita/services/karmanager_spec.rb, spec/lita/services/lunch_assigner_spec.rb
- Se agrega endpoint
```
POST /karma/transfer
{
"receiver_id": "id_usuario_slack"
}
```
- Se agrega `amount` a método `#transfer_karma`
- Se agregan tests para todos los endpoint de la API
- Se arregla un test que esperaba un valor incorrecto
=> feat(api): transfer karma

lib/lita/handlers/api/lunch.rb, lib/lita/handlers/lunch_reminder.rb, spec/lita/handlers/api/lunch_spec.rb
- Endpoint para transferir almuerzo
```
POST /lunches/transfer
{
"receiver": "mention name de usuario"
}
```
Los headers son los mismos de siempre.
- Se arregla un error al usar `DateTime.current`, que solo existe en Rails
=> Transfer lunch endpoint

lib/lita/handlers/lunch_reminder.rb, lib/lita/services/market_manager.rb, spec/lita/handlers/lunch_reminder_spec.rb
Ahora se puede usar el **Market de Ham** con **Slack**. Por ahora sólo se pueden dejar órdenes de venta publicadas _(no se pueden dejar órdenes de compra)_.
- Se creó la ruta para vender un almuerzo diciendo `@ham vende mi almuerzo`. 
- Se creó la ruta para comprar un almuerzo diciendo `@ham compro almuerzo`.
Si cada orden se ejecuta correctamente, se manda un mensaje por interno al usuario y además se publica en el grupo cooking.
---
Algunos cambios que tuve que hacer:
- El método `place_market_order` de Market Manager ahora retorna la orden con la que hizo match en caso de hacerlo.
- broadcast_to_audit_channel ahora quedó estructurado para poder transmitir a un canal pasado como parámetro.
=> feat(Market): Market integration with slack

lib/lita/handlers/api/market.rb, lib/lita/handlers/lunch_reminder.rb, lib/lita/services/market_manager.rb, locales/en.yml, locales/es.yml, spec/lita/handlers/api/market_spec.rb, spec/lita/handlers/lunch_reminder_spec.rb, spec/lita/services/market_manager_spec.rb
- Se eliminó el método `add_market_order`.
- Se crea `transaction_possible?` que retorna `true` si es posible realizar una transacción
- Se crean métodos para obtener las `ask` y `bid` orders
- Se eliminó el endpoint `place_market_order`
- Se adaptó el endpoint `place_limit_order`. Para simplificarlo se creó el método `add_limit_order`
- Se adaptó el código para funcionar sólo con limit orders
- Se crea el método `execute_transactions` para verificar si hay transacciones
- Al ingresar una order (`bid` o `ask`) se verifica si hay alguna transacción
=> feat(market): place bid orders without ask orders

lib/lita/handlers/lunch_reminder.rb, lib/lita/services/market_manager.rb, spec/lita/handlers/lunch_reminder_spec.rb, spec/lita/services/market_manager_spec.rb
Ham se caía porque en `execute_transaction`, accedía a los usuarios usando `symbols`. Ahora se accede todos los hashes usando `strings`.
Adapté también los test para que funcionen con el cambio.
=> Fix lunch market

lib/lita/handlers/api/market.rb, spec/lita/handlers/api/market_spec.rb
Al hacer un `POST` a `market/limit_orders`, los parámetros se debían obtener usando symbols.
=> fix(market): symbolize request params in place_limit_order

lib/lita-lunch-reminder.rb, lib/lita/handlers/lunch_reminder.rb, lib/lita/services/karma_emitter.rb, lib/lita/services/karmanager.rb, locales/en.yml, locales/es.yml, spec/lita/handlers/lunch_reminder_spec.rb, spec/lita/services/karma_emitter_spec.rb
Se implementa emisión/distribución de karma cada 30 días.
Reglas:
- Se divide el karma que tiene ham por el número de usuarios, y se reparte en partes iguales para todos. La división es entera, y lo que sobra se lo queda ham.
- Hay un límite a la riqueza, si alguien tiene más karma que eso no se le da karma.
- Si alguien tiene N y la faltan D para llegar al límite, se le da el mínimo entre D y lo que le corresponde en la repartija.
=> Emit karma

README.md, lib/lita/handlers/lunch_reminder.rb
- Se definen constantes con el valor de los strings correspondientes a los canales de cooking y de audit
- El cliente de `slack-ruby-client` requiere que el nombre esté sin `#`, por lo que en esa llamada se remueve
=> feat(lunch-reminder): get channels from environment variables

lib/lita/handlers/lunch_reminder.rb, lib/lita/services/market_manager.rb, locales/es.yml
Este PR permite eliminar órdenes de compra y venta de almuerzos. Se agregan los métodos necesarios a `market_manager` y los respectivos mensajes de ayuda
Se aprovecha de arreglar un bug en dos endpoints: había `return`s en vez de `next`s. Esto no era grave porque el mono seguía corriendo pero la ejecución de dicha `route` se cortaba y se levantaba una excepción que quedaba loggeada.
=> Cancel orders

lib/lita/handlers/lunch_reminder.rb
Se agregan botones como alternativa para responder la pregunta del almuerzo. Depende de https://github.com/platanus/ham/pull/52
=> feat(lunch-reminder): add buttons to lunch question

README.md, lib/lita/handlers/lunch_reminder.rb, lib/lita/services/karmanager.rb, locales/es.yml
Este PR agrega la posibilidad de sapear la lista de los karmas de todos los almorzadores. Agrega el comando `show me the money` (con el equivalente `muestrame la lista de karma`) para esto, pero responde privadamente por lo largo del mensaje. Agrega la posibilidad de que se postee en el canal de audit segun la variable de entorno `KARMA_LIST_CRON`.
=> Karma list

lib/lita-lunch-reminder.rb, lib/lita/handlers/api/market.rb, lib/lita/handlers/lunch_reminder.rb, lib/lita/services/market_manager.rb, locales/en.yml, locales/es.yml, spec/lita/handlers/api/market_spec.rb, spec/lita/handlers/lunch_reminder_spec.rb, spec/lita/services/market_manager_spec.rb
Viva el libre mercado!
Se permite vender y comprar a más de 1 karma. 
Los comandos:
- compro almuerzo a 3 karmas (y algunas variaciones)
- vendo almuerzo a 2 karmas (y algunas variaciones)
Situaciones:
- Si hay alguien vendiendo a 2, y alguien compra a 2, se ejecuta la transacción
- Si hay alguien vendiendo a 2, y alguien compra a 1, no se ejecuta transacción
- Si hay alguien vendiendo a 1, y alguien compra a 2, entonces SÍ se ejecuta una transacción pero al precio de venta (en este caso, a 1)
- Si hay 5 personas comprando a 1, y 1 persona comprando a 2, y alguien vende a 2, se ejecuta la transacción con la persona vendiendo a 2.
- Si hay 5 personas comprando a 2, y una persona vende a 2, se ejecuta la transacción con la persona que puso la orden primero.
- Se dan casos raros con cómo …
=> Free market

README.md, lib/lita/handlers/lunch_reminder.rb
Se usa un `cron` (parece que el `in` funciona cuando quiere no más)
Se resetean las ordenes para evitar que se pongan antes del sorteo
=> Fix lunch assignment

locales/en.yml, locales/es.yml, spec/lita/handlers/lunch_reminder_spec.rb
Se cambian las traducciones del libro de órdenes para mejorar visibilidad, cambiando de orden los emojis y poniendo el Vendiendo y Comprando en **bold**
=> feat(locales): change order book translations

spec/lita/services/lunch_assigner_spec.rb
El resultado de `pick_winners` tiene una componente no determinista, por lo que el test no debería chequear exactamente quienes son los ganadores
=> fix(lunch-assigner-spec): avoid checking for exact winners

lib/lita/services/weighted_picker.rb, spec/lita/services/lunch_assigner_spec.rb, spec/lita/services/weighted_picker_spec.rb
Se elimina el efecto de la riqueza en la probabilidad de ser elegido. Todos los empatados tendrán la misma probabilidad.
=> feat(assignment): remove impact of wealth in the probability of being chosen

lib/lita/handlers/lunch_reminder.rb, spec/lita/handlers/lunch_reminder_spec.rb
Este PR tiene dos objetivos:
1) Hacer que se pueda transferir más de un karma con un solo comando
2) Hacer que sea más fácil dar karma. Todas estas variantes serían aceptadas:
- suéltale 84 karma a pepin
- dale 10 a juan
- pasale 23 karmas a cholito
- transfierele karma a jose
=> feat(handlers/lunch_reminders): flexibilize transfer command

lib/lita/handlers/lunch_reminder.rb, spec/lita/handlers/lunch_reminder_spec.rb
Al haber una transacción en que el comprador ofrecía más que el vendedor, esta se realizaba al precio de venta pero la notificación de slack se hacía al precio de compra.
Se cambió la notificación de slack usando el precio salido de la transacción.
=> fix(transaction): fix transaction message giving wrong price
